#!/bin/sh

#
# Test credentials in the current checkout.
#
# Usage:
#   ./test/05_test-creds
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

# Set environment variables.
. ./.config

# TODO: Test our Docker registry credentials.
