#!/bin/sh

#
# Test build the specified Dockerfile.
#
# Usage:
#   ./test/10_test-build Dockerfile
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

# Set environment variables.
. ./.config

# Test build:
if command -v docker >/dev/null 2>&1; then
  docker build -f "${1:-Dockerfile}" -t image .
else
  echo " "
  echo "Did not find docker. Run this command:"
  echo "docker build -f ${1:-Dockerfile} -t image ." image
  echo " "
fi
