#!/bin/bash
# Add pull request comment

# Requires these, provided in action.yml:
# - ADD_PR_COMMENT (skip unless "Yes")
# - PR_COMMENT_TOKEN (fail if empty)
# - PR_NUMBER (skip if empty)
# - GH_REPO (repository in owner/repo format)
# - Current working directory is in the config repo

_planfile="${GITHUB_WORKSPACE}/octodns-sync.plan"

if [ "${ADD_PR_COMMENT}" != "Yes" ]; then
  echo "SKIP: \$ADD_PR_COMMENT is not 'Yes'."
  exit 0
fi

if [ -z "${PR_COMMENT_TOKEN}" ] || [ "${PR_COMMENT_TOKEN}" = "Not set" ]; then
  echo "FAIL: \$PR_COMMENT_TOKEN is not set."
  exit 1
fi

if [ -z "${PR_NUMBER}" ]; then
  echo "SKIP: \$PR_NUMBER is not set."
  echo "Was this workflow run triggered from a pull request?"
  exit 0
fi

if ! command -v gh &>/dev/null; then
  echo "FAIL: gh CLI is not available. Install it or use a GitHub-hosted runner."
  exit 1
fi

if [ ! -f "${_planfile}" ]; then
  echo "WARN: Plan file not found at ${_planfile}"
  echo "SKIP: No plan output to comment."
  exit 0
fi

echo "INFO: Posting plan as comment on PR #${PR_NUMBER}."

# Build comment body in a temp file to support large planfiles
_sha="$(git log -1 --format='%h')"
_bodyfile="$(mktemp)"
trap 'rm -f "${_bodyfile}"' EXIT

{
  echo "## octoDNS Plan for ${_sha}"
  echo ""
  cat "${_planfile}"
  echo ""
  echo "Automatically generated by octodns-sync"
} > "${_bodyfile}"

GH_TOKEN="${PR_COMMENT_TOKEN}" \
  gh pr comment "${PR_NUMBER}" \
  --repo "${GH_REPO}" \
  --body-file "${_bodyfile}"
