---
name: Lint Code Base

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint YAML files
        run: yamllint --no-warnings ./

      - name: Lint shell scripts
        run: shellcheck ./scripts/*.sh
