name: Update major tag

on:
  # Run when a release is published (not on draft creation or tag push)
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-tags:
    name: Update major version tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git client
        run: |
          _user="${{ github.repository_owner }}"
          _email="${_user}@users.noreply.github.com"
          git config user.name "${_user}"
          git config user.email "${_email}"

      - name: Update major version tag
        run: |
          _tag="${{ github.event.release.tag_name }}"  # v3.2.0
          _major="${_tag%%.*}"                          # v3
          _msg="Release ${_tag}"

          git tag -fa "${_major}" -m "${_msg}"
          git push --force origin "${_major}"
